/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import controller.DataAnggotaController;

/**
 *
 * @author HP
 */
public class HalamanAnggota extends javax.swing.JFrame {

    /**
     * Creates new form HalamanAnggota
     */
    DataAnggotaController dc;
    
    public HalamanAnggota(String id_admin) {
        initComponents();
        dc = new DataAnggotaController(this);
        dc.isitabel();
        setJlabadmin(id_admin);
        String adminid = getJlabadmin().getText();
        jlabadmin.setText(adminid);
    }
//    String adminid;
//    void getAdminid(String adminid){
//        this.adminid = adminid;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlabadmin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabeltampilanggota = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        jtxtnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxttempatlahir = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxttanggallahir = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtalamat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtgender = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxttelepon = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnkembali = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtxtidanggota = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setText("ADMIN");

        jlabadmin.setText("-");

        tabeltampilanggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeltampilanggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeltampilanggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabeltampilanggota);

        jLabel2.setText("NAMA LENGKAP");

        btnlogout.setBackground(new java.awt.Color(255, 153, 153));
        btnlogout.setText("LOGOUT");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        jLabel3.setText("TEMPAT LAHIR");

        jLabel4.setText("TANGGAL LAHIR");

        jLabel5.setText("ALAMAT");

        jLabel6.setText("GENDER");

        jLabel7.setText("TELEPON");

        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnkembali.setText("KEMBALI");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });

        jLabel8.setText("ID ANGGOTA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlabadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtidanggota)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtxtgender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                                .addComponent(jtxtalamat, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxttanggallahir, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxttempatlahir, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxtnama, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxttelepon))
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                        .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jlabadmin)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnlogout)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(4, 4, 4)
                        .addComponent(jtxtidanggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxttempatlahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxttanggallahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkembali))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MainView v = new MainView();
        v.setVisible(true);
        v.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        dc.insert();
        jtxtidanggota.setText("");
        jtxtnama.setText("");
        jtxttempatlahir.setText("");
        jtxttanggallahir.setText("");
        jtxtalamat.setText("");
        jtxtgender.setText("");
        jtxttelepon.setText("");
        dc.isitabel();
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        dc.update();
        jtxtidanggota.setText("");
        jtxtnama.setText("");
        jtxttempatlahir.setText("");
        jtxttanggallahir.setText("");
        jtxtalamat.setText("");
        jtxtgender.setText("");
        jtxttelepon.setText("");
        dc.isitabel();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        dc.delete();
        jtxtidanggota.setText("");
        jtxtnama.setText("");
        jtxttempatlahir.setText("");
        jtxttanggallahir.setText("");
        jtxtalamat.setText("");
        jtxtgender.setText("");
        jtxttelepon.setText("");
        dc.isitabel();
        
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        // TODO add your handling code here:
        String adminid = getJlabadmin().getText();
        Halamanutama v = new Halamanutama(adminid);
        v.setVisible(true);
        v.setLocationRelativeTo(null);
        System.out.println(adminid);
        this.dispose();
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void tabeltampilanggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeltampilanggotaMouseClicked
        // TODO add your handling code here:
        int baris = tabeltampilanggota.getSelectedRow();
        jtxtidanggota.setText(tabeltampilanggota.getValueAt(baris, 0).toString());
        jtxtnama.setText(tabeltampilanggota.getValueAt(baris, 2).toString());
        jtxttempatlahir.setText(tabeltampilanggota.getValueAt(baris, 3).toString());
        jtxttanggallahir.setText(tabeltampilanggota.getValueAt(baris, 4).toString());
        jtxtalamat.setText(tabeltampilanggota.getValueAt(baris, 5).toString());
        jtxtgender.setText(tabeltampilanggota.getValueAt(baris, 6).toString());
        jtxttelepon.setText(tabeltampilanggota.getValueAt(baris, 7).toString());
        jtxtidanggota.setEditable(false);
    }//GEN-LAST:event_tabeltampilanggotaMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        jtxtidanggota.setText("");
        jtxtnama.setText("");
        jtxttempatlahir.setText("");
        jtxttanggallahir.setText("");
        jtxtalamat.setText("");
        jtxtgender.setText("");
        jtxttelepon.setText("");
        jtxtidanggota.setEditable(true);
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanAnggota("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabadmin;
    private javax.swing.JTextField jtxtalamat;
    private javax.swing.JTextField jtxtgender;
    private javax.swing.JTextField jtxtidanggota;
    private javax.swing.JTextField jtxtnama;
    private javax.swing.JTextField jtxttanggallahir;
    private javax.swing.JTextField jtxttelepon;
    private javax.swing.JTextField jtxttempatlahir;
    private javax.swing.JTable tabeltampilanggota;
    // End of variables declaration//GEN-END:variables
    
    
    public JLabel getJlabadmin() {
        return jlabadmin;
    }

    public void setJlabadmin(String id_admin) {
        this.jlabadmin.setText(id_admin);
    }

    public JTextField getJtxtalamat() {
        return jtxtalamat;
    }

    public void setJtxtalamat(JTextField jtxtalamat) {
        this.jtxtalamat = jtxtalamat;
    }

    public JTextField getJtxtgender() {
        return jtxtgender;
    }

    public void setJtxtgender(JTextField jtxtgender) {
        this.jtxtgender = jtxtgender;
    }

    public JTextField getJtxtnama() {
        return jtxtnama;
    }

    public void setJtxtnama(JTextField jtxtnama) {
        this.jtxtnama = jtxtnama;
    }

    public JTextField getJtxttanggallahir() {
        return jtxttanggallahir;
    }

    public void setJtxttanggallahir(JTextField jtxttanggallahir) {
        this.jtxttanggallahir = jtxttanggallahir;
    }

    public JTextField getJtxttelepon() {
        return jtxttelepon;
    }

    public void setJtxttelepon(JTextField jtxttelepon) {
        this.jtxttelepon = jtxttelepon;
    }

    public JTextField getJtxttempatlahir() {
        return jtxttempatlahir;
    }

    public void setJtxttempatlahir(JTextField jtxttempatlahir) {
        this.jtxttempatlahir = jtxttempatlahir;
    }

    public JTable getTabeltampilanggota() {
        return tabeltampilanggota;
    }

    public void setTabeltampilanggota(JTable tabeltampilanggota) {
        this.tabeltampilanggota = tabeltampilanggota;
    }

    public JTextField getJtxtidanggota() {
        return jtxtidanggota;
    }

    public void setJtxtidanggota(JTextField jtxtidanggota) {
        this.jtxtidanggota = jtxtidanggota;
    }
    
}
