/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;
import controller.databukucontroller;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Lenovo
 */
public class Halamanutama extends javax.swing.JFrame {

    /**
     * Creates new form Halamanutama
     */
    databukucontroller dc;
    public Halamanutama(String id_admin) {
        initComponents();
        dc = new databukucontroller(this);
        dc.isitabel();
        System.out.println("Berhasil Masuk Halaman Utama");
        setJlabadmin(id_admin);
        String adminid = getJlabadmin().getText();
//        getAdminid(adminid);
        jlabadmin.setText(adminid);

        //db = new databukucontroller(this);
        //db.isitabel();
        //setJlabadmin(int id_admin);
    }
//    String adminid;
//    void getAdminid(String adminid){
//        this.adminid = adminid;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabletampilbuku = new javax.swing.JTable();
        jtxttitle = new javax.swing.JTextField();
        jtxtauthor = new javax.swing.JTextField();
        jtxtpublisher = new javax.swing.JTextField();
        jtxtyear = new javax.swing.JTextField();
        jtxtqty = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlabkeluar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jtxtidbuku = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jlabadmin = new javax.swing.JLabel();
        btnpeminjaman = new javax.swing.JButton();
        btnriwayat = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        btneditadmin = new javax.swing.JButton();
        btnanggota1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(876, 524));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        tabletampilbuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabletampilbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabletampilbukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabletampilbuku);

        jtxtauthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtauthorActionPerformed(evt);
            }
        });

        jtxtpublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtpublisherActionPerformed(evt);
            }
        });

        jLabel1.setText("TITLE");

        jLabel2.setText("AUTHOR");

        jLabel3.setText("PUBLISHER");

        jLabel4.setText("YEAR");

        jLabel5.setText("QTY");

        jlabkeluar.setText("-");

        jLabel7.setText("Dipinjam :");

        jLabel8.setText("ID BUKU");

        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        jtxtidbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtidbukuActionPerformed(evt);
            }
        });

        jLabel6.setText("ADMIN");

        jlabadmin.setText("-");

        btnpeminjaman.setText("PEMINJAMAN");
        btnpeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpeminjamanActionPerformed(evt);
            }
        });

        btnriwayat.setText("RIWAYAT PEMINJAMAN");
        btnriwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnriwayatActionPerformed(evt);
            }
        });

        btnlogout.setBackground(new java.awt.Color(249, 19, 19));
        btnlogout.setText("LOGOUT");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        btneditadmin.setText("EDIT ADMIN");
        btneditadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditadminActionPerformed(evt);
            }
        });

        btnanggota1.setText("DAFTAR ANGGOTA");
        btnanggota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanggota1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxttitle)
                            .addComponent(jtxtauthor)
                            .addComponent(jtxtpublisher)
                            .addComponent(jtxtyear)
                            .addComponent(jtxtqty)
                            .addComponent(jtxtidbuku)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnlogout))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlabkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnanggota1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(btnsimpan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addGap(41, 41, 41)))
                                                .addGap(18, 18, 18)
                                                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 120, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlabadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 699, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnpeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(btnriwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btneditadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jlabadmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(btnlogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxttitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2)
                        .addGap(2, 2, 2)
                        .addComponent(jtxtauthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtpublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4)
                        .addGap(2, 2, 2)
                        .addComponent(jtxtyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtidbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jlabkeluar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsimpan)
                            .addComponent(btndelete)
                            .addComponent(btnupdate)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btneditadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnanggota1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnriwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtpublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtpublisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtpublisherActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        dc.insert();
        jtxtidbuku.setText("");
        jtxttitle.setText("");
        jtxtauthor.setText("");
        jtxtpublisher.setText("");
        jtxtyear.setText("");
        jtxtqty.setText("");
        jlabkeluar.setText("-");
        dc.isitabel();
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        dc.update();
        jtxtidbuku.setText("");
        jtxttitle.setText("");
        jtxtauthor.setText("");
        jtxtpublisher.setText("");
        jtxtyear.setText("");
        jtxtqty.setText("");
        jlabkeluar.setText("-");
        dc.isitabel();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void jtxtauthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtauthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtauthorActionPerformed

    private void jtxtidbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtidbukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtidbukuActionPerformed

    private void tabletampilbukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabletampilbukuMouseClicked
        // TODO add your handling code here:
        int baris = tabletampilbuku.getSelectedRow();
        jtxtidbuku.setText(tabletampilbuku.getValueAt(baris, 0).toString());
        jtxttitle.setText(tabletampilbuku.getValueAt(baris, 2).toString());
        jtxtauthor.setText(tabletampilbuku.getValueAt(baris, 3).toString());
        jtxtpublisher.setText(tabletampilbuku.getValueAt(baris, 4).toString());
        jtxtyear.setText(tabletampilbuku.getValueAt(baris, 5).toString());
        jtxtqty.setText(tabletampilbuku.getValueAt(baris, 6).toString());
        jlabkeluar.setText(tabletampilbuku.getValueAt(baris, 7).toString());
        jtxtidbuku.setEditable(false);
    }//GEN-LAST:event_tabletampilbukuMouseClicked

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MainView v = new MainView();
        v.setVisible(true);
        v.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        dc.delete();
        jtxtidbuku.setText("");
        jtxttitle.setText("");
        jtxtauthor.setText("");
        jtxtpublisher.setText("");
        jtxtyear.setText("");
        jtxtqty.setText("");
        jlabkeluar.setText("-");
        dc.isitabel();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnriwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnriwayatActionPerformed
        // TODO add your handling code here:
//        HalamanAnggota ha = new HalamanAnggota(jlabadmin.getText());
//        ha.setVisible(true);
//        ha.setLocationRelativeTo(null);
//        System.out.println(jlabadmin.getText());
//        this.dispose();
        Halamanriwayat v = new Halamanriwayat(jlabadmin.getText());
        v.setVisible(true);
        v.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnriwayatActionPerformed

    private void btneditadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditadminActionPerformed
        // TODO add your handling code here:
        RegisterAdmin v = new RegisterAdmin(jlabadmin.getText());
        v.setVisible(true);
        v.setLocationRelativeTo(null);
        System.out.println(jlabadmin.getText());
        this.dispose();
    }//GEN-LAST:event_btneditadminActionPerformed

    private void btnpeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpeminjamanActionPerformed
        // TODO add your handling code here:
        Halamanpeminjaman v = new Halamanpeminjaman(jlabadmin.getText());
        v.setVisible(true);
        v.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnpeminjamanActionPerformed

    private void btnanggota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanggota1ActionPerformed
        // TODO add your handling code here:
        HalamanAnggota v = new HalamanAnggota(jlabadmin.getText());
        v.setVisible(true);
        v.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnanggota1ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        jtxtidbuku.setText("");
        jtxttitle.setText("");
        jtxtauthor.setText("");
        jtxtpublisher.setText("");
        jtxtyear.setText("");
        jtxtqty.setText("");
        jlabkeluar.setText("-");
        jtxtidbuku.setEditable(true);
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Halamanutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Halamanutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Halamanutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Halamanutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Halamanutama("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnanggota1;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btneditadmin;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnpeminjaman;
    private javax.swing.JButton btnriwayat;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabadmin;
    private javax.swing.JLabel jlabkeluar;
    private javax.swing.JTextField jtxtauthor;
    private javax.swing.JTextField jtxtidbuku;
    private javax.swing.JTextField jtxtpublisher;
    private javax.swing.JTextField jtxtqty;
    private javax.swing.JTextField jtxttitle;
    private javax.swing.JTextField jtxtyear;
    private javax.swing.JTable tabletampilbuku;
    // End of variables declaration//GEN-END:variables

    
    public JLabel getJlabkeluar() {
        return jlabkeluar;
    }

    public void setJlabkeluar(JLabel jlabkeluar) {
        this.jlabkeluar = jlabkeluar;
    }

    public JTextField getJtxtauthor() {
        return jtxtauthor;
    }

    public void setJtxtauthor(JTextField jtxtauthor) {
        this.jtxtauthor = jtxtauthor;
    }

    public JTextField getJtxtpublisher() {
        return jtxtpublisher;
    }

    public void setJtxtpublisher(JTextField jtxtpublisher) {
        this.jtxtpublisher = jtxtpublisher;
    }

    public JTextField getJtxtqty() {
        return jtxtqty;
    }

    public void setJtxtqty(JTextField jtxtqty) {
        this.jtxtqty = jtxtqty;
    }

    public JTextField getJtxttitle() {
        return jtxttitle;
    }

    public void setJtxttitle(JTextField jtxttitle) {
        this.jtxttitle = jtxttitle;
    }

    public JTextField getJtxtyear() {
        return jtxtyear;
    }

    public void setJtxtyear(JTextField jtxtyear) {
        this.jtxtyear = jtxtyear;
    }

    public JTable getTabletampilbuku() {
        return tabletampilbuku;
    }

    public void setTabletampilbuku(JTable tabletampilbuku) {
        this.tabletampilbuku = tabletampilbuku;
    }

    public JTextField getJtxtidbuku() {
        return jtxtidbuku;
    }

    public void setJtxtidbuku(JTextField jtxtidbuku) {
        this.jtxtidbuku = jtxtidbuku;
    }

    public JLabel getJlabadmin() {
        return jlabadmin;
    }

    public void setJlabadmin(String id_admin) {
        this.jlabadmin.setText(id_admin);
    }

}
