/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import controller.datariwayatcontroller;
import controller.datapinjamcontroller;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author Lenovo
 */
public class Halamanriwayat extends javax.swing.JFrame {

    /**
     * Creates new form Halamanriwayat
     */
    datariwayatcontroller dra;
    datapinjamcontroller dpa;
    public Halamanriwayat(String id_admin) {
        initComponents();
        labeladmin.setText(id_admin);
        dra = new datariwayatcontroller(this);
        dpa = new datapinjamcontroller(this);
        dra.isitabel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableriwayat = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jinputstatus = new javax.swing.JComboBox<>();
        btnsubmit = new javax.swing.JButton();
        labelidpinjam = new javax.swing.JLabel();
        labelidanggota = new javax.swing.JLabel();
        labelnamalengkap = new javax.swing.JLabel();
        labelidbuku = new javax.swing.JLabel();
        labeltitle = new javax.swing.JLabel();
        labelidadmin = new javax.swing.JLabel();
        labeltglpinjam = new javax.swing.JLabel();
        labeltglkembali = new javax.swing.JLabel();
        labelqty = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labeladmin = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableriwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableriwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableriwayatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableriwayat);

        jLabel1.setText("ID PINJAM");

        jLabel2.setText("ID_ANGGOTA");

        jLabel3.setText("NAMA_LENGKAP");

        jLabel4.setText("ID_BUKU");

        jLabel5.setText("TITLE");

        jLabel6.setText("ID ADMIN");

        jLabel7.setText("TGL PINJAM");

        jLabel8.setText("TGL_KEMBALI");

        jLabel9.setText("QTY");

        jLabel10.setText("STATUS");

        jinputstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Kembali", "Sudah Kembali", "Hilang" }));

        btnsubmit.setText("SUBMIT");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        labelidpinjam.setText("-");

        labelidanggota.setText("-");

        labelnamalengkap.setText("-");

        labelidbuku.setText("-");

        labeltitle.setText("-");

        labelidadmin.setText("-");

        labeltglpinjam.setText("-");

        labeltglkembali.setText("-");

        labelqty.setText("-");

        jLabel11.setText("ID ADMIN");

        labeladmin.setText("-");

        jButton1.setText("<- Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jinputstatus, 0, 107, Short.MAX_VALUE)
                                    .addComponent(labelidpinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelidanggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelnamalengkap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelidbuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labeltitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelidadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labeltglpinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labeltglkembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelqty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(100, 100, 100))
                            .addComponent(labeladmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(labelidpinjam))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(labelidanggota))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(labelnamalengkap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(labelidbuku))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(labeltitle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(labelidadmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(labeltglpinjam))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(labeltglkembali))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(labelqty))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jinputstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsubmit))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(labeladmin)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
        dpa.update();
        dpa.update2();
        dra.isitabel();
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void tableriwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableriwayatMouseClicked
        // TODO add your handling code here:
        int baris = tableriwayat.getSelectedRow();
        labelidpinjam.setText(tableriwayat.getValueAt(baris, 0).toString());
        labelidanggota.setText(tableriwayat.getValueAt(baris, 1).toString());
        labelnamalengkap.setText(tableriwayat.getValueAt(baris, 2).toString());
        labelidbuku.setText(tableriwayat.getValueAt(baris, 3).toString());
        labeltitle.setText(tableriwayat.getValueAt(baris, 4).toString());
        labelidadmin.setText(tableriwayat.getValueAt(baris, 5).toString());
        labeltglpinjam.setText(tableriwayat.getValueAt(baris, 6).toString());
        labeltglkembali.setText(tableriwayat.getValueAt(baris, 7).toString());
        labelqty.setText(tableriwayat.getValueAt(baris, 8).toString());
        String nilaiDariTabel = tableriwayat.getValueAt(baris, 9).toString();
        jinputstatus.setSelectedItem(nilaiDariTabel);
    }//GEN-LAST:event_tableriwayatMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String adminid = labeladmin.getText();
        Halamanutama v = new Halamanutama(adminid);
        v.setVisible(true);
        v.setLocationRelativeTo(null);
        System.out.println(adminid);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Halamanriwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Halamanriwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Halamanriwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Halamanriwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Halamanriwayat("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jinputstatus;
    private javax.swing.JLabel labeladmin;
    private javax.swing.JLabel labelidadmin;
    private javax.swing.JLabel labelidanggota;
    private javax.swing.JLabel labelidbuku;
    private javax.swing.JLabel labelidpinjam;
    private javax.swing.JLabel labelnamalengkap;
    private javax.swing.JLabel labelqty;
    private javax.swing.JLabel labeltglkembali;
    private javax.swing.JLabel labeltglpinjam;
    private javax.swing.JLabel labeltitle;
    private javax.swing.JTable tableriwayat;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getJinputstatus() {
        return jinputstatus;
    }

    public void setJinputstatus(JComboBox<String> jinputstatus) {
        this.jinputstatus = jinputstatus;
    }

    public JLabel getLabelidadmin() {
        return labelidadmin;
    }

    public void setLabelidadmin(JLabel labelidadmin) {
        this.labelidadmin = labelidadmin;
    }

    public JLabel getLabelidanggota() {
        return labelidanggota;
    }

    public void setLabelidanggota(JLabel labelidanggota) {
        this.labelidanggota = labelidanggota;
    }

    public JLabel getLabelidbuku() {
        return labelidbuku;
    }

    public void setLabelidbuku(JLabel labelidbuku) {
        this.labelidbuku = labelidbuku;
    }

    public JLabel getLabelidpinjam() {
        return labelidpinjam;
    }

    public void setLabelidpinjam(JLabel labelidpinjam) {
        this.labelidpinjam = labelidpinjam;
    }

    public JLabel getLabelnamalengkap() {
        return labelnamalengkap;
    }

    public void setLabelnamalengkap(JLabel labelnamalengkap) {
        this.labelnamalengkap = labelnamalengkap;
    }

    public JLabel getLabelqty() {
        return labelqty;
    }

    public void setLabelqty(JLabel labelqty) {
        this.labelqty = labelqty;
    }

    public JLabel getLabeltglkembali() {
        return labeltglkembali;
    }

    public void setLabeltglkembali(JLabel labeltglkembali) {
        this.labeltglkembali = labeltglkembali;
    }

    public JLabel getLabeltglpinjam() {
        return labeltglpinjam;
    }

    public void setLabeltglpinjam(JLabel labeltglpinjam) {
        this.labeltglpinjam = labeltglpinjam;
    }

    public JLabel getLabeltitle() {
        return labeltitle;
    }

    public void setLabeltitle(JLabel labeltitle) {
        this.labeltitle = labeltitle;
    }

    public JTable getTableriwayat() {
        return tableriwayat;
    }

    public void setTableriwayat(JTable tableriwayat) {
        this.tableriwayat = tableriwayat;
    }

    public JLabel getLabeladmin() {
        return labeladmin;
    }

    public void setLabeladmin(String id_admin) {
        this.labeladmin.setText(id_admin);
    }

    
    
//    private void initComponents() {
//        // Inisialisasi komponen
//
//        // Menyiapkan editor khusus untuk sel pada baris yang tidak dapat diklik
//        tableriwayat.setDefaultEditor(Object.class, new DefaultCellEditor(new JTextField()) {
//            @Override
//            public boolean isCellEditable(EventObject anEvent) {
//                // Memeriksa jika baris tersebut dapat diklik atau tidak
//                int row = tableriwayat.getSelectedRow();
//                return !barisTidakDapatDiklik(row);
//            }
//        });
//
//        // Konfigurasi lainnya
//    }
//
//    // Metode lainnya
//
//    private boolean barisTidakDapatDiklik(int baris) {
//        // Logika untuk menentukan apakah baris tertentu tidak dapat diklik
//        // Anda dapat mengganti logika ini dengan kondisi yang sesuai dengan aplikasi Anda
//        return baris % 2 == 0; // Contoh: baris genap tidak dapat diklik
//    }
//
//    // Metode lainnya
//}

}
